version: "3"
services:
  mysql:
    build: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: "crms"
      MYSQL_USER: "crms"
      MYSQL_PASSWORD: "crms"
      MYSQL_ROOT_PASSWORD: "crms"
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log/:/var/log/mysql
