spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crs?useSSL=false&allowPublicKeyRetrieval=true
    username: crs
    password: crs
    driver: com.mysql.cj.jdbc.Driver

  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    outOfOrder: false
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver: ${spring.datasource.driver}
    locations: classpath:db/migration

crs:
  package: dev.abelab.crs
  mybatis:
    config:
      file: generatorConfig.xml
    model:
      package: db.entity
    client:
      package: db.mapper
      type: XMLMAPPER
    map:
      package: db.mapper

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapperLocations:
    - classpath:/db/mapper/*Mapper.xml
