spring:
  datasource:
    url: jdbc:mysql://localhost:3307/crms?useSSL=false&allowPublicKeyRetrieval=true
    username: crms
    password: crms
    driver: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: ERROR
