spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crms?useSSL=false&allowPublicKeyRetrieval=true
    username: crms
    password: crms
    driver: com.mysql.cj.jdbc.Driver

crms:
  protocol: https
  hostname: api.abelab.dev/crms

jwt:
  secret: zdtlD3JK56m6wTTgsNFhqzjq
  issuer: crms.abelab.dev
