spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crms?useSSL=false&allowPublicKeyRetrieval=true
    username: crms
    password: crms
    driver: com.mysql.cj.jdbc.Driver

springfox.documentation.swagger.v2.host: api.abelab.dev/crms
