spring:
  datasource:
    url:
    username:
    password:
    driver:
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    outOfOrder: false
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver: ${spring.datasource.driver}
    locations: classpath:db/migration
  messages:
    basename: i18n/messages
    encoding: UTF-8

server:
  port: 8080

crms:
  package: dev.abelab.crms
  mybatis:
    config:
      file: generatorConfig.xml
    model:
      package: db.entity
    client:
      package: db.mapper
      type: XMLMAPPER
    map:
      package: db.mapper

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapperLocations:
    - classpath:/db/mapper/*Mapper.xml

logging:
  level:
    root: INFO
